server:
  address: "http://localhost"
  port:  8001

mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  db: "url_shortener"

redis:
  host: "localhost"
  port: 6379

worker:
  size: 10
