version: "3"
services:
  mysql:
    image: mysql:8.0.38
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-url_shortener}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    ports:
      - "3306:3306"
    networks:
      - mysql

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "28080:8080"
    networks:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${CONFIG_FOLDER}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - url-shortener
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3003"
    volumes:
      - ${CONFIG_FOLDER}/grafana/provisioning:/etc/grafana/provisioning
      - ${CONFIG_FOLDER}/grafana/dashboards:/var/lib/grafana/dashboards
      - ${CONFIG_FOLDER}/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_HTTP_PORT: 3003
      GF_SERVER_PROTOCOL: http
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - prometheus

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "28082:8081"
    depends_on:
      - redis
    networks:
      - redis

  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - jaeger

  url-shortener:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - jaeger
    ports:
      - "8001:8001"
    networks:
      - url-shortener
      - mysql
      - redis
      - jaeger

networks:
  url-shortener: {}
  mysql: {}
  prometheus: {}
  redis: {}
  jaeger: {}